<a href="https://colab.research.google.com/github/maicg01/python-image-processing/blob/main/Face_Recognition.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install face-recognition

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 100.1 MB 1.2 MB/s 
  Created wheel for face-recognition-models: filename=face_recognition_models-0.3.0-py2.py3-none-any.whl size=100566186 sha256=a6403010a8c57c3c571f8b2efc4736cecc52a3b840de0666eb3534e7a0e33da0
  Stored in directory: /root/.cache/pip/wheels/d6/81/3c/884bcd5e1c120ff548d57c2ecc9ebf3281c9a6f7c0e7e7947a
Successfully built face-recognition-models


In [2]:
import face_recognition
import numpy as np

# Find our first face

In [46]:
image = face_recognition.load_image_file('/content/l4.jpg')
face_locs = face_recognition.face_locations(image, number_of_times_to_upsample=1, model='cnn')

In [47]:
# How many faces did we find?
len(face_locs), type(face_locs)

(1, list)

In [48]:
face_locs[0]

(100, 1745, 830, 1015)

In [49]:
face_encodings = face_recognition.face_encodings(image, known_face_locations=face_locs)

In [50]:
face_encodings[0]

array([-0.02880775,  0.11623754,  0.03988955, -0.09952827, -0.05783321,
       -0.04382946, -0.06673955, -0.11459268,  0.18870632, -0.13486308,
        0.24877101, -0.02460719, -0.21853617, -0.06573989, -0.0694925 ,
        0.21480298, -0.18822199, -0.16477743, -0.04432398,  0.03604757,
        0.0755446 ,  0.01942538,  0.10100816,  0.05229309, -0.09511022,
       -0.38871217, -0.08260096, -0.03958886, -0.01345153, -0.03514732,
       -0.08760068,  0.03482522, -0.20488855, -0.02488526,  0.04075976,
        0.04652302, -0.04869699, -0.08096983,  0.26579836,  0.05715219,
       -0.29006484,  0.03370918,  0.01099823,  0.26950544,  0.21010771,
        0.01934591,  0.0355855 , -0.18590808,  0.13996215, -0.20632416,
        0.05093342,  0.15938464,  0.0427476 ,  0.00403084, -0.023127  ,
       -0.06574616,  0.00537951,  0.15210597, -0.17974348, -0.03138904,
        0.0958055 , -0.13299266, -0.06942061, -0.13544801,  0.2649453 ,
        0.13120183, -0.13585779, -0.2040996 ,  0.16807301, -0.13

In [51]:
# How many datapoints do we have?
len(face_encodings[0])

128

# Grab second face

In [52]:
image2 = face_recognition.load_image_file('/content/l3.jpg')
face_locs2 = face_recognition.face_locations(image2, number_of_times_to_upsample=0, model='cnn')
face_encodings2 = face_recognition.face_encodings(image2, known_face_locations=face_locs2)
face_encodings2[0]

array([-0.04987139,  0.07285649, -0.02310571, -0.03382243, -0.09067659,
        0.01458315, -0.08128209, -0.07541824,  0.13492414, -0.13766325,
        0.19368951, -0.04014997, -0.27649903, -0.06918239, -0.06897119,
        0.15403876, -0.14617036, -0.15364416,  0.00631099,  0.0259738 ,
        0.09036095,  0.1195057 , -0.02009334,  0.02962956, -0.10469195,
       -0.31634209, -0.13855444, -0.05249979, -0.01294544, -0.07882641,
       -0.06576085,  0.04818692, -0.14841206, -0.02502811,  0.07484594,
        0.06978939,  0.01789743, -0.00411807,  0.17593981,  0.03495966,
       -0.25879854,  0.06163831,  0.07852415,  0.3098534 ,  0.23292102,
        0.02710325, -0.0274925 , -0.18611181,  0.13207971, -0.1431482 ,
        0.06082477,  0.18019621,  0.10362656,  0.07195948, -0.02372964,
       -0.10954085,  0.0316363 ,  0.11494671, -0.15270238,  0.00108538,
        0.12234466, -0.07003982,  0.03917808, -0.00645727,  0.14173692,
       -0.07389437, -0.11027242, -0.24562122,  0.10563672, -0.25

# Compare our faces

### Euclidean Distances

Where dist `<= .6` is a match

In [56]:
# How do we calculate euclidean distances?

# Distance between 3 + 7 = abs(3-7) or abs(d1-d2) => 4

abs(3-7)

4

In [57]:
# Grab the first datapoint from both matricies
face_encodings[0][0], face_encodings2[0][0]

(-0.028807751834392548, -0.04987138882279396)

In [58]:
# Subtract them => 0.0245
# This is the linear distance between the two points
face_encodings[0][0] - face_encodings2[0][0]

0.021063636988401413

In [59]:
# Do this for every value matrix value (double check with first value) => 0.0245
(face_encodings - face_encodings2[0])[0][0]

0.021063636988401413

In [60]:
# Let's define this matrix of euclidean distances
distances_matrix = face_encodings - face_encodings2[0]
distances_matrix

array([[ 2.10636370e-02,  4.33810577e-02,  6.29952662e-02,
        -6.57058395e-02,  3.28433774e-02, -5.84126124e-02,
         1.45425424e-02, -3.91744375e-02,  5.37821800e-02,
         2.80016661e-03,  5.50815016e-02,  1.55427773e-02,
         5.79628646e-02,  3.44249606e-03, -5.21317124e-04,
         6.07642233e-02, -4.20516282e-02, -1.11332685e-02,
        -5.06349658e-02,  1.00737698e-02, -1.48163512e-02,
        -1.00080311e-01,  1.21101502e-01,  2.26635337e-02,
         9.58172977e-03, -7.23700821e-02,  5.59534803e-02,
         1.29109286e-02, -5.06091863e-04,  4.36790809e-02,
        -2.18398273e-02, -1.33617036e-02, -5.64764887e-02,
         1.42851844e-04, -3.40861753e-02, -2.32663676e-02,
        -6.65944163e-02, -7.68517517e-02,  8.98585469e-02,
         2.21925303e-02, -3.12663019e-02, -2.79291272e-02,
        -6.75259195e-02, -4.03479636e-02, -2.28133053e-02,
        -7.75733963e-03,  6.30780011e-02,  2.03728676e-04,
         7.88244605e-03, -6.31759614e-02, -9.89134982e-0

In [61]:
# How do we evaluate this matrix?

# < insert Frobenius norm theory / proof >

In [62]:
# Find the Frobenius norm of our distance matrix by:
# - Adding the square of every vector to `dist_sum`
# - Finding the square root of `dist_sum`

dist_sum = 0
for vector in distances_matrix[0]:
  dist_sum = dist_sum + vector**2

fro_norm = dist_sum**(1/2)
fro_norm

0.6110380843348021

In [63]:
# Or as a one-liner

fro_norm = sum([x**2 for x in distances_matrix[0]])**(1/2)
fro_norm

0.6110380843348021

In [64]:
# This is what numpy is doing with the `.norm` function:
np.linalg.norm(distances_matrix)

0.6110380843348023

In [65]:
# The face_recognition library will do this all behind the scenes.
# You only have to pass it two matricies:

face_recognition.face_distance(face_encodings, face_encodings2[0])

array([0.61103808])

In [66]:
# From the standard library, any norm <= .6 is a match, and 0.0 is a perfect match
# Where `True` is a match and `False` is not 
face_recognition.compare_faces(face_encodings, face_encodings2[0])

[False]

In [67]:
face_recognition.face_distance(face_encodings, face_encodings[0])

array([0.])

### Cosine Similarity

In [23]:
# Cosine similarity can find similarities that can't be found using Euclidiean distances
# It works especially well for multi-dimensional comparisons

# < Cosine similarity theory >

# similarity = cos(theta) = dot_product(A and B) / (norm(A) * norm(B))

In [24]:
# Use the zip() function to get values from both matricies at the same time
# These are the first 5 values for face1 and face2:
face_encodings[0][:5], face_encodings2[0][:5]

(array([-0.12511465,  0.07453115,  0.06925846,  0.01487394, -0.14306593]),
 array([-0.14236905,  0.07431981,  0.06662806,  0.06331547, -0.08340718]))

In [25]:
# Here's how the zip function combines them:
[(v1, v2) for v1, v2 in zip(face_encodings[0], face_encodings2[0])][:5]

[(-0.12511464953422546, -0.14236904680728912),
 (0.07453114539384842, 0.07431980967521667),
 (0.06925845891237259, 0.06662806123495102),
 (0.014873940497636795, 0.06331547349691391),
 (-0.1430659294128418, -0.08340717852115631)]

In [26]:
# Loop through all vectors and multiply them to find the Euclidean dot product
dot_product = sum(v1*v2 for v1, v2 in zip(face_encodings[0], face_encodings2[0]))
dot_product

1.9496613818476918

In [27]:
# And find the Frobenius norms for our matricies
norm_a = sum([x**2 for x in face_encodings[0]])**(1/2)
norm_b = sum([x**2 for x in face_encodings2[0]])**(1/2)

norm_a, norm_b

(1.4346300009205597, 1.394031439452347)

In [28]:
# Then combine the dot product and norms to calculate cosine similarity:
cos_sim = dot_product/(norm_a * norm_b)
cos_sim

0.9748700146139828

In [29]:
# Now let's use the built-in cosine similarity function to check our answer
from sklearn.metrics import pairwise
pairwise.cosine_similarity(face_encodings, face_encodings2)

array([[0.97487001]])

In [30]:
# Since cosine similarity = cos(theta), 
# we can call arccos(cos_sim) to find the angle
# between our two matricies:
np.arccos(cos_sim)

0.2246595164330463

In [31]:
# Our two matrices are .28 radians apart...
# In degrees, that is:
import math
math.degrees(np.arccos(cos_sim))

12.872042119063515

In [32]:
# A perfect match would have an angle equal to 0 between our two points...
# and since cos(0) == 1, a perfect match would be 1:
pairwise.cosine_similarity(face_encodings, face_encodings)

array([[1.]])

### Normalize NP Dots

In [ ]:
def compare_faces(f1, f2):
    def normalize(embedding):
        embedding_norm = np.linalg.norm(embedding)
        normed_embedding = embedding / embedding_norm
        return normed_embedding

    f1 = normalize(f1)
    f2 = normalize(f2)

    return (1. + np.dot(f1, f2)) / 2

In [ ]:
compare_faces(face_encodings, face_encodings2[0])

array([0.97988125])